sources:
  - name: Hygraph
    handler:
      graphql:
        endpoint: https://api-eu-central-1.hygraph.com/v2/ck8sn5tnf01gc01z89dbc7s0o/master
    transforms:
      - prefix:
          value: Hygraph_
  - name: CartQL
    handler:
      graphql:
        endpoint: https://api.cartql.com
    transforms:
      - prefix:
          value: CartQL_
  - name: SpaceX
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql/
    transforms:
      - prefix:
          value: SpaceX_
